### PR TITLE
Add setuid and setgid capabilities on Unix.

### PR DESCRIPTION
**Pull request by Tyler-Hardin**
I can't test that this still builds on Windows and I'm pretty unfamiliar with the cfg system. Sorry if there are errors.

### CODE REVIEW

**Comment by hniksic** [comment]
Thanks for the pull request, the functionality is useful. I would like to see a few minor changes before merging it:

* Move `Exec::uid` and `Exec::gid` to an `unix::ExecExt` extension trait. This pattern is often seen in the stdlib, where [`OsStrExt`](https://doc.rust-lang.org/std/os/unix/ffi/trait.OsStrExt.html) implements Unix-specific methods for [`OsStr`](https://doc.rust-lang.org/std/ffi/struct.OsStr.html), [`CommandExt`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html) for [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html), etc. The explicit trait has to be imported manually, which prevents writing non-portable code by accident.

* Return `io::Error` produced by [`Error::last_os_error()`](https://doc.rust-lang.org/std/io/struct.Error.html#method.last_os_error) when `setuid` or `setgid` fail. This ensures that the actual `errno` is properly preserved, and that the correct system error message issued to the user. Ideally `libc::setuid` and `libc::setgid` would be wrapped in `posix.rs` and provide a safe interface, calling `check_err` for the error checking. (Note that `popen.rs` itself contains no unsafe code.)

**Comment by hniksic** [comment]
@Tyler-Hardin Are you still interested in working on this?

**Comment by Tyler-Hardin** [comment]
@hniksic, yes, will try to finish it up this weekend. Thanks for your patience.

**Comment by hihellobolke** [comment]
Was going to open an issue, found this pull request! Waiting for this! Thanks

**Comment by hniksic** [comment]
@hihellobolke @Tyler-Hardin An implementation of `setuid` and `setgid` that fixes the issues found in the review is now on master.

**Pull request closed without merging**
