### PR TITLE
Add `Exec.to_string()` and `Pipeline.to_string()`

### PR DESCRIPTION
**Pull request by ElPicador**
The purpose of this PR is to have ready to use display functions for `Exec` & `Pipeline`.

Happy to discuss the output of the `fmt` functions.

### CODE REVIEW

**Comment by hniksic** [comment]
I like this idea. Two remarks:

* the commit message mentions `to_string()`, but the patch seems to implement `Display::fmt`.
* we probably want the displayed string to quote the arguments that contain whitespace, the same way the OS shell would. For example, `Exec::cmd("command").arg("foo").arg("bar")` should display different than `Exec::cmd("command").arg("foo bar")`.

**Comment by ElPicador** [comment]
@hniksic Done!

**Comment by ElPicador** [comment]
@hniksic Done. WDYT?

**Comment by hniksic** [comment]
It's very close. Your `contains_metachar` checks for control characters and whitespace, but not for other shell metacharacters, such as `*`, `?`, `|`, `&`, quote chars, backslash, and possibly others. I'd replace the lines:

```rust
                let contains_quote = arg_as_str.contains("'");
                let contains_metachar = arg_as_str.chars().any(|c| c.is_control() || c.is_whitespace());
```

with:

```rust
                let needs_quote = arg_as_str.chars().any(|c| !c.is_ascii_alphanumeric());
```

This will also quote arguments that contain punctuations such as `_`, but that shouldn't be a problem in practice.

**Comment by hniksic** [comment]
Another thing: in display code, you probably want to use [`path.to_string_lossy()`](https://doc.rust-lang.org/1.15.1/std/path/struct.Path.html#method.to_string_lossy) in preference to `path.to_string().unwrap_or("")`. That will leave replacement characters to indicate that parts of the argument could not be fully converted.

**Comment by ElPicador** [comment]
Done!

**Comment by hniksic** [comment]
Looking at the changes, there's seems to be a left-over `self.command.to_str().unwrap_or("")`.

**Comment by hniksic** [comment]
I've added your changes with minor improvements to the formatting routine - instead of building a vector of args, you can simply call `write!()` in the loop. Also, I made it so often-used characters like `.`, `-`, and `/` don't cause quoting.

**Comment by hniksic** [comment]
I've looked a bit more at how the `Display` trait is used in Rust, and it seems more fit for data that has a good human-readable representation, such as strings and numbers. For example, even containers don't define `Display`. They do define `Debug`, however.

Should `Exec` and `Pipeline` define a custom `Debug` trait instead, so that printing them with `{:?}` prints a nicer output?

**Comment by ElPicador** [comment]
I'm sorry but this is going too far for me. I'm not using this library any more, but I was willing to finish the PR based on your reviews. 
As I need to redo everything, I'm not willing to pursue this any more. Feel free to change the code as you see fit!

**Comment by hniksic** [comment]
@ElPicador Your contribution is still appreciated and will make it into `subprocess`. If I can just ask you, what was your use case for defining the `Display` trait?

**Comment by ElPicador** [comment]
I'm developing a CLI that runs some shell commands.
And I wanted to display to the user the command ran when if it fails.

Something like (probably not compiling):
```rust
let directory: &str = ...;
let ls = Exec::cmd("ls").arg("-l").arg(directory);
let wc = Exec::cmd("wc").arg("-l");
let cmd = ls | wc;

match cmd.capture() {
  Err(e) => println!("failed to run command {}: {}", cmd, e)
  Ok(r) => ...
}

[...]
```

I didn't want to construct the command twice: one for display, one to use it with subprocess.
The idea was only to have an error message, not for the user to be able to copy/paste it and run it manually.

I used the `{:?}` in the `println`, but it displayed internal state as well as the command run.

**Comment by hniksic** [comment]
Thanks for the clarification. I am asking because `Exec` has a number of additional options that are not reflected in the `Display::fmt` we are adding, and I'm not sure if that breaks the contract of `Display`.

I'll definitely leave *some* way of accessing this string because I think it's useful, maybe it'll just need to be explicitly requested with `cmd.to_string_lossy()` or something like that. That will ensure the caller to be aware that there is no one-to-one correspondence between the string and the actual command.

**Comment by ElPicador** [comment]
Closing this as it seems not useful anymore

**Pull request closed without merging**
