### PR TITLE
feat(output): Add CaptureOutput.success(), Capture.success() 

### PR DESCRIPTION
**Pull request by ElPicador**
This PR add a helper method to `CaputureOutput` to know if the pipeline was successful
It also correct a typo in `ExitStatus.success()` method.

### CODE REVIEW

**Comment by hniksic** [comment]
Thanks, this looks like it could reduce the amount of typing for simple commands. Should the same `success()` method be added to `builder::exec::Capture`?

**Comment by ElPicador** [comment]
@hniksic Done 😄

**Comment by hniksic** [comment]
Thanks! Just one nit: the first commit appears to include output from some automated reformatting tool. I don't mind the changes, but could you move them to a separate commit? Ideally one commit would contain the new methods, and the other the code the formatting tweaks.

**Comment by ElPicador** [comment]
Sorry about that, I've not seen that my editor reformatted the code :/
I've removed the reformatting, and put the 2 changes in 1 commit

**Pull request merged**
