### PR TITLE
add CREATE_NO_WINDOW for gui mode

### PR DESCRIPTION
**Pull request by woodgear**
//it will popup a black console windows in windows
#![windows_subsystem = "windows"] 
extern crate subprocess;

use subprocess::{Exec,Redirection};
use std::io::{BufReader, BufRead};
use std::io::prelude::*;
use std::fs::File;

fn main() {
    let out = Exec::cmd("dir")
	.stdout(Redirection::Pipe)
	.capture().unwrap()
  	.stdout_str();
	println!("{}",out);
	let mut file = File::create("out.txt").unwrap();
	file.write_all(&out.into_bytes()).unwrap();
}

### CODE REVIEW

**Comment by hniksic** [comment]
Is it safe to specify `CREATE_NO_WINDOW` unconditionally? Neither Rust's `Command` nor Python's `subprocess.Popen` are doing it. Rust specifies `DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP` if a `detach` flag is turned on, but the code appears dead - there doesn't seem to be a way to turn it on using the `std::process` API.

**Comment by woodgear** [comment]
how about add a method called no_windows in builder which use like Exec::cmd("ls").no_window().stream_stdout().unwrap()

**Comment by hniksic** [comment]
This would probably require a platform-specific extension module, but it would be acceptable.

What about the question of implementation? Should it use `CREATE_NO_WINDOW` or `DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP`? Is there reliable documentation on how to do this properly?

**Comment by hniksic** [comment]
@woodgear Just a ping regarding the `CREATE_NO_WINDOW` or `DETACHED_PROCESS` question.

According to [this stackoverflow answer](https://stackoverflow.com/a/10753521/1600898), the difference is that `DETACHED_PROCESS` is disallowed from talking to the parent's console. This seems like a good idea when starting a non-trusted process.

**Comment by hniksic** [comment]
@woodgear , Any news on this one?

**Comment by hniksic** [comment]
Closing due to lack of response by the submitter.

**Pull request closed without merging**
